### PR TITLE
[WIP] Remove unused Dockerfile and add Snyk dependency

### PR DESCRIPTION
**Pull request by klssmith**
**Use concourse docker file for local development**
We were using the old Jenkins Dockerfile before, which had a very old version of Node so gave different results when installing dependencies when compared to the Concourse Dockerfile.

**Add Snyk dependency and `prepare` command**
This cherry-picks the commits from https://github.com/alphagov/notifications-node-client/pull/117 but adds an extra commit to fix the Dockerfile and package.json so that they work.

### CODE REVIEW

**Comment by CrystalPea** [comment]
What would be a good way to review this PR / check the changes work as expected?

**Comment by klssmith** [comment]
To test that nothing breaks you can try building the Dockerfile locally - that _should_ be fine though because I have tried that locally. I think the main thing I'd like an opinion on is the approach taken in the last commit.

**Comment by CrystalPea** [comment]
Hey, nothing breaks, I do not know enough to comment on the command change. But if it works, it's something, right?

Also, there are those two commits `test` and `wip`, and the latter has some commands to execute as sudo, is this temporary?

**Comment by klssmith** [comment]
I decided to take another look at this, which is why there are currently a couple of temporary commits at the end (I've added [WIP] to the title to make that clear now). The original PR did work but is a bit hacky - I'd like to find a nicer way of getting it to work

**Comment by CrystalPea** [comment]
Ahh, ok, sounds good, ganbatte! 💖

**Pull request closed without merging**
